### ISSUE TITLE
Separately publish executable files for caddy with webdav plugin.

### ISSUE THREAD

**Issue by masx200** [mholt/caddy-webdav#12]
Separately publish executable files for caddy with webdav plugin.
https://github.com/mholt/caddy-webdav/releases

Since webdav requires higher performance than static files and reverse proxy, I think webdav should be run as a separate process, and then it would be better for caddy gateway service to do reverse proxy for webdav.

It is better to separate the gateway service and webdav service into separate processes.

Compiling caddy with plug-ins still has some costs. Wouldn't it be better to publish it as an executable file?

In this way, you can get a webdav server out of the box.

**Comment by wader** [comment]
Is there some reason you could not run same binary but with two different configs? don't want the compiled webdav code in the binary on the gateway even when not used?

**Comment by mholt** [comment]
Yeah, I'm not convinced by the claims this issue makes given what is presented here, nor that this plugin needs to be packaged as a binary; will close, but feel free to discuss if necessary.
