### ISSUE TITLE
How to set up a basic webdav server.

### ISSUE THREAD

**Issue by NetHeritage** [mholt/caddy-webdav#14]
**What I am trying to do?**
1. Directory for web hosting:  /var/www/html
2. Directory for webdav sharing: /var/www/webdav
3. Username and password are not need to browse the website, but users need to offer correct username and password to access webdav sharing. 
4. User with the right  username and password can read and write any files in /var/www/webdav. Anyone else cannot read or write the folder.

**Caddyfile I use:**

{
order webdav last
}
www.example.com {
	root * /var/www/html
	file_server browse
	tls {
	dns cloudflare CLOUDFLARE-API-TOKEN
	}
	webdav {
	root /var/www/webdav
	}
	basicauth {
	webdav JDJhJDE0JFJNbjZYOVhROXhFSGEwaUkzWTdQTnVYUTVvWWt6UnFlLmlIa2R2aVBKZnQyR0RtdXBYTXpx
	}
}

**Caddy Output**
root@ubuntu:~# systemctl status caddy
● caddy.service - Caddy
     Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-10-12 14:05:28 UTC; 17min ago
       Docs: https://caddyserver.com/docs/
   Main PID: 2534 (caddy)
      Tasks: 9 (limit: 9258)
     CGroup: /system.slice/caddy.service
             └─2534 /usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile

Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.0924478,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.096836,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]}
Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.0975156,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x4000119960"}
Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.0976834,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port>
Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.0977411,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.1013224,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["www.example.com"]}
Oct 12 14:05:28 ubuntu caddy[2534]: {"level":"info","ts":1602511528.1027489,"logger":"tls","msg":"cleaned up storage units"}
Oct 12 14:05:58 ubuntu caddy[2534]: {"level":"warn","ts":1602511558.1394393,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [www.example.com]: making OCSP request: Post \"http://ocsp.int-x3.letsencrypt.org\": di>
Oct 12 14:05:58 ubuntu caddy[2534]: {"level":"info","ts":1602511558.1402895,"msg":"autosaved config","file":"/var/lib/caddy/.config/caddy/autosave.json"}
Oct 12 14:05:58 ubuntu caddy[2534]: {"level":"info","ts":1602511558.1403522,"msg":"serving initial configuration"}

**OS & Caddy version info:**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**root@ubuntu:~# caddy version**
v2.2.1-0.20200926000008-85152679ce91 h1:eEFYtKRMhq8FJC7z3/2B+Ay2oWPuur0fiLRnj11yjRU=

**root@ubuntu:~# caddy list-modules**
admin.api.load
admin.api.metrics
caddy.adapters.caddyfile
caddy.listeners.tls
caddy.logging.encoders.console
caddy.logging.encoders.filter
caddy.logging.encoders.filter.delete
caddy.logging.encoders.filter.ip_mask
caddy.logging.encoders.json
caddy.logging.encoders.logfmt
caddy.logging.encoders.single_field
caddy.logging.writers.discard
caddy.logging.writers.file
caddy.logging.writers.net
caddy.logging.writers.stderr
caddy.logging.writers.stdout
caddy.storage.file_system
dns.providers.cloudflare
http
http.authentication.hashes.bcrypt
http.authentication.hashes.scrypt
http.authentication.providers.http_basic
http.encoders.gzip
http.encoders.zstd
http.handlers.acme_server
http.handlers.authentication
http.handlers.encode
http.handlers.error
http.handlers.file_server
http.handlers.forward_proxy
http.handlers.headers
http.handlers.map
http.handlers.metrics
http.handlers.push
http.handlers.request_body
http.handlers.reverse_proxy
http.handlers.rewrite
http.handlers.static_response
http.handlers.subroute
http.handlers.templates
http.handlers.vars
http.handlers.webdav
http.matchers.expression
http.matchers.file
http.matchers.header
http.matchers.header_regexp
http.matchers.host
http.matchers.method
http.matchers.not
http.matchers.path
http.matchers.path_regexp
http.matchers.protocol
http.matchers.query
http.matchers.remote_ip
http.matchers.vars
http.matchers.vars_regexp
http.reverse_proxy.selection_policies.first
http.reverse_proxy.selection_policies.header
http.reverse_proxy.selection_policies.ip_hash
http.reverse_proxy.selection_policies.least_conn
http.reverse_proxy.selection_policies.random
http.reverse_proxy.selection_policies.random_choose
http.reverse_proxy.selection_policies.round_robin
http.reverse_proxy.selection_policies.uri_hash
http.reverse_proxy.transport.fastcgi
http.reverse_proxy.transport.http
pki
tls
tls.certificates.automate
tls.certificates.load_files
tls.certificates.load_folders
tls.certificates.load_pem
tls.handshake_match.sni
tls.issuance.acme
tls.issuance.internal
tls.issuance.zerossl
tls.stek.distributed
tls.stek.standard

**What did I get:**
Caddy do not generate any error. After input username-password to browse the static html files in /var/www/html.  I can connect webdav server via winscp after input username-password, but can not add any files in the folder, I got a 404 error. I cannot map it as a drive on Windows 10, too.

![image](https://user-images.githubusercontent.com/588329/95757960-66152e00-0cda-11eb-84bd-40cc64904abe.png)

**Comment by NetHeritage** [comment]
![Uploading image.png…]()

**Comment by NetHeritage** [comment]
![image](https://user-images.githubusercontent.com/588329/95758408-0703e900-0cdb-11eb-90b0-71c39437f1a6.png)

**Comment by wader** [comment]
Could it be that `root *` will match all requests so they don't reach webdav?

**Comment by mholt** [comment]
@wader Close! `root` doesn't do anything except set a variable; it's always a pass-thru (non-terminal) handler. 

@NetHeritage's mistake is using `order webdav last` which puts it after `file_server`, because last means last. So the file_server handles the request first, which is a terminal handler. OP simply needs to follow readme instructions: https://github.com/mholt/caddy-webdav#syntax
