### ISSUE TITLE
How to use webdav on caddy docker

### ISSUE THREAD

**Issue by Joyace** [mholt/caddy-webdav#18]
Hello! Friend.

I use this caddy. https://hub.docker.com/_/caddy?tab=description
But webdav can not work.
Can you help me ?

Thank you very much.

**Comment by Joyace** [comment]
I read the official website.
Module http.handlers.webdav does not come with Caddy.
Then, how to add webdav in caddy docker ?

**Comment by mholt** [comment]
Closing in favor of duplicated thread in forum: https://caddy.community/t/how-to-use-webdav-on-caddy-docker-compose/10730?u=matt

**Comment by JoJenH** [comment]
I saw your question in the Caddy community, but it seems that the issue has been closed, so I couldn't reply there. I see it again here. Your Dockerfile build looks fine, but Caddy is not running. I suspect that your run command is overriding the original run command of Caddy. You need to add a command to start Caddy after your xcaddy command, such as caddy run.
