### ISSUE TITLE
Is it possible to have directory listing with WebDAV enabled in the same path?

### ISSUE THREAD

**Issue by rekacant** [mholt/caddy-webdav#20]
Based on the documents and my test, it seems like WebDAV has to be served in a different path with directory listing, one cannot have them both functioning under the same path, is that correct?

As an Apache & Nginx user, I felt quite surprised, as it is an expected behaviour to have them working in the same path.

Cheers,
Jayden

**Comment by wader** [comment]
Haven't tried but maybe you could somehow combine `method GET { ... }` and `{http.matchers.file.type}` to make `browse` handle those request? I think that should be fine as WebDAV useu `PROPLIST` method for directories.

**Comment by Zeethulhu** [comment]
Using [matchers ](https://caddyserver.com/docs/caddyfile/matchers) is probably the way to go.

This may work for you. (Untested)

```
localhost:80 {

@notget {
  not method GET
  }

    root * /www
    file_server browse
    webdav @notget
}
```

**Comment by noerw** [comment]
With the proper order it works, thanks!

```
{
  order webdav before file_server
}

localhost

@notget {
  not method GET
}

root * /www
webdav @notget 
file_server browse
```
