### ISSUE TITLE
Excuse me, how to set different permissions under multiple users?

### ISSUE THREAD

**Issue by underlaw** [mholt/caddy-webdav#27]
For example, user 1 has read, write, edit and delete permission, while user 2 has only read permission.

**Comment by mholt** [comment]
Depends on how you're authenticating users and such. What is your config / what have you tried so far?

**Comment by underlaw** [comment]
thx

:2333
{
encode gzip
basicauth {
underlaw JDJhJDE0JDI1OUJCR3VndzBWUWtSU3ZsdVJXUGVrLzlsV0M2N3AuN2taRmkvY2ZnMlVIR1VtZnE4bjN5
test JDJhJDE0JDI1OUJCR3VndzBWUWtSU3ZsdVJXUGVrLzlsV0M2N3AuN2taRmkvY2ZnMlVIR1VtZnE4bjN5
}
root * /mnt/sda1/movie

route {
        rewrite /webdav /webdav/
        webdav /webdav/* {
                prefix /webdav
        }
        file_server browse
}
}

underlaw has read, write, edit and delete permission; test  has only read permission.

how to do? thx

**Comment by mholt** [comment]
You could probably use something like:

```
@forbidWrite {
    vars http.auth.user.id test
    not method GET HEAD OPTIONS PROPFIND
}
handle @forbidWrite {
    respond "Not allowed" 403
}
handle {
    # everything else
}
```

**Comment by underlaw** [comment]
Are you talking about setting different shared folders for different users? This is different from what I want. I want the same shared folder, but different users have different permissions. Thank you

**Comment by underlaw** [comment]
I mean: the shared folder is /mnt/sda1/movie, undelaw has read-write permission, and test only has read permission.

**Comment by mholt** [comment]
No, that's disallowing writes for the user named `test`.

With further questions, please try asking on our forums! https://caddy.community

**Comment by SoSolife** [comment]
> No, that's disallowing writes for the user named `test`.
> 
> With further questions, please try asking on our forums! https://caddy.community

But it also disallow read files from server on applications that support webdav when `test` remove method `PROPFIND`.
And it retains method `PROPFIND`, `test` can delete files from server.
Just want to share friends with accounts and not to modify files on sever.

**Comment by arichiardi** [comment]
Came here to say thank you @mholt - this is the only solution that works here - I can see files but not modify them.

with this conf:

```
:8080 {
    rewrite /dav /dav/

        # Thank you mholt for this solution:
        #   https://github.com/mholt/caddy-webdav/issues/27
    @noGuestsWrite {
        vars http.auth.user.id guest
        not method GET HEAD OPTIONS PROPFIND
    }
    handle @noGuestsWrite {
        respond 403
    }
    handle {
        basicauth /dav/media {
            guest <XYZ>
        }

        webdav /dav/* {
            root /srv/http/dav/All
            prefix /dav/media
        }
        file_server
    }
}
```
