### ISSUE TITLE
Empty response from Caddy + Webdav

### ISSUE THREAD

**Issue by nestarz** [mholt/caddy-webdav#3]
Hello, I'm using caddy1 + webdav and would like to migrate, but this version of the webdav plugin gives me empty responses, except on the root path where I get the xml right.

Thanks,

Response (on any request except / )
```
HTTP/1.1 200 OK
Server: Caddy
Date: Fri, 22 May 2020 23:04:21 GMT
Content-Length: 0
```

Caddyfile
```
{
	order webdav last
}

:2015 {
    webdav / {
		root ./
	}
}
```

**Comment by wader** [comment]
I think the issue might be that path matchers are [by default exact](https://caddyserver.com/docs/caddyfile/matchers#path-matchers). Try to change `webdav /` to `webdav /*`.

**Comment by nestarz** [comment]
Thanks for your fast support,
I still have empty response with this path matcher.

This is the request:
```
GET /out/ HTTP/1.1
Host: 192.168.0.104:62121
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

And the answer
```
HTTP/1.1 200 OK
Server: Caddy
Date: Fri, 22 May 2020 23:21:08 GMT
Content-Length: 0
```

Note that the first answer is not empty and look like this:
```
HyperCommons
HTTP/1.1 207 Multi-Status
Content-Type: text/xml; charset=utf-8
Server: Caddy
Date: Fri, 22 May 2020 23:21:05 GMT
Transfer-Encoding: chunked

800
<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/</D: (truncated)
```

**Comment by nestarz** [comment]
It's working ! Thanks a lot !

**Comment by wader** [comment]
Oh good, was reading your reply, just tested wrong first time?

**Comment by mholt** [comment]
You can just get rid of the matcher entirely: https://caddyserver.com/docs/caddyfile/matchers

> Matcher tokens are usually optional. If a matcher token is omitted, it is the same as a wildcard matcher (`*`).

**Comment by wader** [comment]
@mholt good point!

**Comment by nestarz** [comment]
@wader Forgot to restart my Caddy server like a rookie 😬 Thanks ! 
I am trying to use this project to let people mount a folder and share it using the Hyperswarm protocol

**Comment by wader** [comment]
@nestarz aha happens to everyone 😄
