### ISSUE TITLE
The webdav service filter some files for unknown reason

### ISSUE THREAD

**Issue by xtay573269555** [mholt/caddy-webdav#31]
The caddy and webdav module is downloaded today from the homepage.

Caddyfile : 
```
{
    admin off
    auto_https off
    local_certs
    order webdav before file_server
}

:9999 {
    encode gzip
    root * /data      
    file_server browse
    tls /root/caddy/server.cert /root/caddy/server.key

    webdav /webdav/* {
        root /data
        prefix /webdav
    }
}
```

# Step 1
Generate some text files as the snapshot, then refresh the webdav directory, no any text file is shown.
<img width="954" alt="snapshot_20221019142605" src="https://user-images.githubusercontent.com/5844466/196613596-3c501df5-4b4e-4229-8fd0-21f7796609bb.png">

# Step 2
Then, just rename the text file to another filetype as the snapshot, and refresh the webdav directory again, one of them appeared.
<img width="939" alt="snapshot_20221019143333" src="https://user-images.githubusercontent.com/5844466/196614498-bc77d12c-877a-482c-a5ba-b5aad8ef1ce1.png">
 
# Step 3
Let's continue. This time i just rename the filename, did not change the filetype. Here is the snapshot.
<img width="944" alt="snapshot_20221019143559" src="https://user-images.githubusercontent.com/5844466/196615174-4508e3de-0d1d-4d1c-bbc7-4fbbd2365531.png">

# Step 4
Not only text files is filtered strangely, other filetype is the same. Here is another test.
<img width="903" alt="snapshot_20221019144319" src="https://user-images.githubusercontent.com/5844466/196616227-55b6dc61-bfbf-4073-ab15-0fddb97de005.png">

This is my webdav client conf:
<img width="547" alt="snapshot_20221019144626" src="https://user-images.githubusercontent.com/5844466/196617210-6d5b1831-9b96-4e27-934f-251a720ed6fe.png">

I dont know why and how to resolve it. Thanks.

**Comment by mholt** [comment]
@xtay573269555 Is this no longer an issue?

Sorry I haven't replied -- been busy -- but I did see this.

**Comment by xtay573269555** [comment]
Yes. It is working well after i delete the folder named "lost+found". The parent directory(/data) is a mount point using a remote disk.

**Comment by xtay573269555** [comment]
It doesnt matter. I sometimes ignoring too.
