### ISSUE TITLE
CF

### ISSUE THREAD

**Issue by stargatecmd2009** [mholt/caddy-webdav#35]
Can we get some support added for chunked uploads / setting max body size ?
I'm trying to use this behind cloudflare proxy and it always fails on large files.

**Comment by mholt** [comment]
Possibly -- what exactly do you have in mind? Are you talking about chunked transfer encoding? https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by mholt** [comment]
Hmm, you can already set a max body size for Caddy: https://caddyserver.com/docs/caddyfile/directives/request_body

It sounds like whatever IPB is doing is splitting the file up client-side and re-assembling it server-side with PHP. Even if we added support for something like this in the webdav module, the webdav client would have to support it.
