### ISSUE TITLE
internal handler error (stat) spam by bad clients (macOS Finder & Windows Explorer)

### ISSUE THREAD

**Issue by PayBas** [mholt/caddy-webdav#47]
My logs are filled with entries such as:
```json
Sep 24 15:14:11 prod3ls.mega.corp caddy[774527]: 
{
  "level": "error",
  "ts": 1727183651.6396859,
  "logger": "http.handlers.webdav",
  "msg": "internal handler error",
  "error": "stat /var/www/propserver/._.: no such file or directory",
  "request": {
    "remote_ip": "172.28.35.122",
    "remote_port": "50187",
    "client_ip": "172.28.35.122",
    "proto": "HTTP/1.1",
    "method": "PROPFIND",
    "host": "propserver.mega.corp",
    "uri": "/._.",
    "headers": {
      "Authorization": [
        "REDACTED"
      ],
      "Content-Length": [
        "179"
      ],
      "Connection": [
        "keep-alive"
      ],
      "Content-Type": [
        "text/xml"
      ],
      "Depth": [
        "0"
      ],
      "Accept": [
        "*/*"
      ],
      "User-Agent": [
        "WebDAVFS/3.0.0 (03008000) Darwin/23.6.0 (arm64)"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 771,
      "cipher_suite": 49199,
      "proto": "",
      "server_name": "propserver.mega.corp"
    }
  }
}
```
I know this is just the macOS Finder doing silly Finder things, but what bothers me so much is that this is dumped to the Journal on `systemd` machines (RedHat/CentOS/Fedora).

So while the virtualhost/server/access log shows a 404 being returned, the underlying `stat /var/www/propserver/._.: no such file or directory` doesn't seem to be handled and gets dumped to the main Caddy process. This floods the logs which makes detecting _actual_ issues much more difficult.

I have no control over my clients, so I see loads of these calls coming in from macOS Finder and Windows Explorer.

Is there some way to prevent these log messages from being output by the main Caddy process? I'd much rather have the errors contained in the actual logs as defined in the caddyfiles.

My `/usr/lib/systemd/system/caddy.service`:
```
[Unit]
Description=Caddy web server
Documentation=https://caddyserver.com/docs/
After=network.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStartPre=/usr/bin/caddy validate --config /etc/caddy/Caddyfile
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

My `/etc/caddy/Caddyfile.d/propserver.caddyfile`
```
propserver.mega.corp:80 {
    redir https://{host}{uri} permanent
}

propserver.mega.corp {
    root * /var/www/propserver
    tls /etc/pki/tls/certs/propserver.mega.corp.chain.pem /etc/pki/tls/private/propserver.mega.corp.key
    encode gzip
    log {
        output file /var/log/caddy/propserver.log
        level INFO
        format console
    }

    handle_errors {
        respond "{err.status_code} {err.status_text}"
    }

    @not-get not method GET HEAD
    route @not-get {
        request_body {
            max_size 10KB
        }
        basic_auth {
            propwriter $2b$12$UYc2rQAiHfHd/EBmiT/b4OLpCWtOIXt6cQCoS6snZ1ilcr8wuGXCC
        }
        webdav
    }

    file_server
}
```

**Comment by mholt** [comment]
You could use matchers in your Caddyfile to block requests for files that don't exist. See the [file matcher](https://caddyserver.com/docs/caddyfile/matchers#file).

But:

> This floods the logs which makes detecting actual issues much more difficult.

Why does this make detection more difficult? Just ignore those lines :man_shrugging:

(Going to close, since I don't think there's anything actionable to be done here, but we can reopen if needed. Feel free to continue the discussion!)

**Comment by PayBas** [comment]
> You could use matchers in your Caddyfile to block requests for files that don't exist. See the [file matcher](https://caddyserver.com/docs/caddyfile/matchers#file).

Using https://caddyserver.com/docs/caddyfile/directives/abort for `/._*` file matchers causes macOS Finder to retry indefinitely, which freezes the connection popup dialog and basically bombards the server with `PROPFIND` requests (which subsequently get dropped).

> Why does this make detection more difficult? Just ignore those lines 🤷‍♂️

We're talking about the systemd journal here, not the https://caddyserver.com/docs/caddyfile/directives/log 

Having it flooded with Caddy internal errors relating to sloppy WebDAV activity by `http.handlers.webdav` is a bad idea. It leads to the Caddy site logs effectively bleeding into the Caddy service logs.

You don't want `journalctl -u caddy.service` to be flooded with this stuff. Just ignoring all `"level":"error"` messages relating to WebDAV is no trivial task. You'd need to pipe the journalctl output through jq and do all kinds of structured filtering (which can be very slow given the volume we're talking about).

Ideally you'd want `journalctl -u caddy.service` to only show service-level logs. Not site-specific WebDAV PROPFIND "file not found" issues (which are bound to happen with WebDAV).

**Comment by wader** [comment]
Was a while since i messed with this code, but what kind of errors are plugin expected to log? and at what level? maybe it would be possible to inspect the err value here https://github.com/mholt/caddy-webdav/blob/master/webdav.go#L93-L98 and behave differently for some file system related errors like "not found" which in this case is not really an error? I can look into it if we can agree on how it should behave.

BTW while poking around I notice a upstream fix https://github.com/golang/go/issues/67150 that has not been included yet.

**Comment by wader** [comment]
For reference, reproduced with:
```
http://0.0.0.0:8080

root * /srv

route {
	webdav /dav/* {
		prefix /dav
	}
	file_server
}
```
```
curl -v -X PROPFIND http://0:8080/dav/bla
```
Log: (req: and err: are my own added logs)
```
2024/09/25 07:20:11.446	INFO	req: &http.Request{Method:"PROPFIND", URL:(*url.URL)(0x140006ae7e0), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept":[]string{"*/*"}, "User-Agent":[]string{"curl/8.7.1"}}, Body:http.noBody{}, GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:0, TransferEncoding:[]string(nil), Close:false, Host:"0.0.0.0:8080", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"127.0.0.1:51470", RequestURI:"/dav/bla", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), Pattern:"", ctx:(*context.valueCtx)(0x140006a8d80), pat:(*http.pattern)(nil), matches:[]string(nil), otherValues:map[string]string(nil)}
2024/09/25 07:20:11.446	INFO	err: &fs.PathError{Op:"stat", Path:"/srv/bla", Err:0x2}
2024/09/25 07:20:11.446	ERROR	http.handlers.webdav	internal handler error	{"error": "stat /srv/bla: no such file or directory", "request": {"remote_ip": "127.0.0.1", "remote_port": "51470", "client_ip": "127.0.0.1", "proto": "HTTP/1.1", "method": "PROPFIND", "host": "0.0.0.0:8080", "uri": "/dav/bla", "headers": {"User-Agent": ["curl/8.7.1"], "Accept": ["*/*"]}}}
```
```Err:0x2``` is probably `ENOENT`

**Comment by mholt** [comment]
@PayBas 

> Just ignoring all "level":"error" messages relating to WebDAV is no trivial task. 

Huh, that sounds like a serious oversight in a log viewer.

Or maybe it is that journald is only a log manager, and not a log viewer.

@wader 

Nice to see you again!

> Was a while since i messed with this code, but what kind of errors are plugins expected to log? and at what level? maybe it would be possible to inspect the err value here https://github.com/mholt/caddy-webdav/blob/master/webdav.go#L93-L98 and behave differently for some file system related errors like "not found" which in this case is not really an error? I can look into it if we can agree on how it should behave.

Yeah, our static file server handler does something like this. We treat "file not found" for example as a non-error in terms of logging (but we still show the 404 status in the log, of course).

**Comment by wader** [comment]
> @wader
> 
> Nice to see you again!

👋  same!

> > Was a while since i messed with this code, but what kind of errors are plugins expected to log? and at what level? maybe it would be possible to inspect the err value here https://github.com/mholt/caddy-webdav/blob/master/webdav.go#L93-L98 and behave differently for some file system related errors like "not found" which in this case is not really an error? I can look into it if we can agree on how it should behave.
> 
> Yeah, our static file server handler does something like this. We treat "file not found" for example as a non-error in terms of logging (but we still show the 404 status in the log, of course).

Make sense, so i wonder in this case what request/error combinations should be ignored... or other other way around what combinations should be logged? ex if we get a `ENOENT` `PathError` is there any request where we expected the path to exist but it didn't? as files could be created/added at any time behind the back of caddy it feels hard to come up with any?

**Comment by mholt** [comment]
What if we just start with ENOENT (I guess that's basically "not found") and see how much that helps improve the situation... because yeah, if the file isn't found, I don't know if there's a way to know whether that's intended or not.

**Comment by wader** [comment]
@PayBas latest commit should log less now

**Comment by PayBas** [comment]
@wader that's awesome. Thank you guys for the quick resolution.

I haven't been able to obtain the latest version because both https://caddyserver.com/download and `caddy add-package` still think that latest == `v0.0.0-20240522223621-0f2910d52a7e`, but I'm guessing it takes some time to propagate and I'll be able to obtain it after a couple of days. (using xcaddy on my particular testing machine is a bit too tricky).

**Comment by mholt** [comment]
The build server is just caching builds (rescan is just for docs).

You can specify a commit in the version textbox of the download page. Or you can use xcaddy: `xcaddy build --with github.com/mholt/caddy-webdav@master` to get the latest commit.

**Comment by PayBas** [comment]
@mholt thanks for clarifying.

I've been able to test it and the systemd journal is indeed much quieter now. So that makes me happy :).

There's still some stuff bleeding through such as:
```json
{"level":"error","ts":1727451978.0731642,"logger":"http.handlers.webdav","msg":"internal handler error","error":"webdav: locked","request":{"remote_ip":"172.28.32.201","remote_port":"61190","client_ip":"172.28.32.201","proto":"HTTP/1.1","method":"PUT","host":"propserver.mega.corp","uri":"/._deliverately%202%20shady.sh","headers":{"Content-Length":["0"],"Connection":["keep-alive"],"User-Agent":["WebDAVFS/3.0.0 (03008000) Darwin/23.6.0 (arm64)"],"Accept":["*/*"],"Authorization":["REDACTED"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","server_name":"propserver.mega.corp"}}}
```
But the spam is basically 90% less 👍

**Comment by mholt** [comment]
@PayBas Great, thanks for the update.

That remaining error is: `// ErrLocked is returned by a LockSystem's Create, Refresh and Unlock methods.` -- not entirely sure what that's all about, but I'm really not a WebDAV guy :sweat_smile:

**Comment by wader** [comment]
No idea either, but I had a quick look at the [webdav spec about locks](http://www.webdav.org/specs/rfc4918.html#locking) and the [various lock errors in the golang webdav implementation](https://github.com/golang/net/blob/master/webdav/lock.go#L16-L25) and i suspect that none of them should be logged as errors, which i assume is reserved for "real" errors not that some client failed to acquire a exclusive resource lock etc? maybe should be logged as info or debug?

**Comment by mholt** [comment]
If it's an error that WebDAV clients are used to receiving and then they simply retry or whatever, then sure, we probably can demote those to DEBUG-level.

**Comment by PayBas** [comment]
Just a heads-up. I'm hesitant to open a separate issue for this.

https://caddyserver.com/download still serves an old `0f2910d52a7ea15517a288a6f3f02a5e010da845` version of the plugin.
`caddy add-package github.com/mholt/caddy-webdav` on a clean install does the same.

So it appears that Caddy isn't picking up on these changes.

**Comment by mholt** [comment]
Our download server caches builds, which are keyed by build configuration which includes version info. If the version is empty or `master` or something like that, any new commits will be keyed the same. Once in a while we clear the build cache, but we really need to implement proper version lookups in those cases. I've just been too busy. In the meantime you can always specify a commit SHA in to get a specific version.

**Comment by PayBas** [comment]
> In the meantime you can always specify a commit SHA in to get a specific version.

Yeah that's what I've been doing. I was under the impression that building with a specific (newer) hash would somehow trigger an update on the download server.
But it doesn't, so while I can grab the needed versions perfectly fine manually, my Ansible setup doesn't do this and still gets the old version.

No big deal, I can simply host the "custom" version internally, but _eventually_ you'd want `latest` to actually reflect the current HEAD of `master` ;).

Anyhow, sorry for sidetracking the original topic.

**Comment by mholt** [comment]
> No big deal, I can simply host the "custom" version internally, but eventually you'd want latest to actually reflect the current HEAD of master ;).

Agreed! Just need to figure out the "right way" to do that lookup. I'm sure there's some Go-tooling-related function somewhere that does this, but I don't know it yet.
