### ISSUE TITLE
Make Missing Caddy 1 WebDav Plugin features available

### ISSUE THREAD

**Issue by Flameborn** [mholt/caddy-webdav#5]
Hello,

Are there plans to expose features available in https://github.com/hacdias/caddy-webdav, such as blocking dot files, allowing modifications for files/folders per user, or allowing/denying user access to resources, for Caddy 2?

I am currently using Caddy v1.

**Comment by mholt** [comment]
Access and authentication features are handled in another part of Caddy, this handler is only for the webdav protocol. Authentication and authorization features can be added to our growing list of auth plugins: https://caddy.community/t/list-of-caddy-2-modules/7839

You can block dot files with request matchers: https://caddyserver.com/docs/json/apps/http/servers/routes#match
