### ISSUE TITLE
Document prefix option

### ISSUE THREAD

**Issue by prcmt** [mholt/caddy-webdav#8]
The readme doesn't document the prefix option at the moment, which is required whenever a matcher is used on the directive.

I spent an hour or two of confusion before finding the option in the code, documenting it might save the next person some time. :D

**Comment by wader** [comment]
Sorry about that 😕 we were talking about fixing this in #7

**Comment by prcmt** [comment]
No worries. I now know 200% more about Caddy 2 than I did before the adventure of debugging my issue - and the fact that the fix was so simple is definitely a happy ending!

**Comment by mholt** [comment]
Thanks so much @wader!
